INSERT INTO producto (nombre, precio) VALUES ('Laptop', 1500.00);
INSERT INTO producto (nombre, precio) VALUES ('Mouse', 50.00);
INSERT INTO producto (nombre, precio) VALUES ('Teclado', 100.00);
INSERT INTO producto (nombre, precio) VALUES ('Monitor', 200.00);
INSERT INTO producto (nombre, precio) VALUES ('Impresora', 500.00);
INSERT INTO producto (nombre, precio) VALUES ('Auriculares', 75.00);
INSERT INTO producto (nombre, precio) VALUES ('Smartphone', 1200.00);
INSERT INTO producto (nombre, precio) VALUES ('Tablet', 800.00);
INSERT INTO producto (nombre, precio) VALUES ('Cámara', 900.00);
INSERT INTO producto (nombre, precio) VALUES ('Disco Duro Externo', 150.00);
INSERT INTO producto (nombre, precio) VALUES ('USB 32GB', 25.00);
INSERT INTO producto (nombre, precio) VALUES ('Router', 120.00);
INSERT INTO producto (nombre, precio) VALUES ('Switch Ethernet', 60.00);
INSERT INTO producto (nombre, precio) VALUES ('Proyector', 1100.00);
INSERT INTO producto (nombre, precio) VALUES ('Smartwatch', 250.00);
INSERT INTO producto (nombre, precio) VALUES ('Cargador Rápido', 30.00);
INSERT INTO producto (nombre, precio) VALUES ('Cable HDMI', 20.00);
INSERT INTO producto (nombre, precio) VALUES ('Teclado Mecánico', 150.00);
INSERT INTO producto (nombre, precio) VALUES ('Alfombrilla para Ratón', 10.00);
INSERT INTO producto (nombre, precio) VALUES ('Caja de Herramientas', 80.00);
INSERT INTO producto (nombre, precio) VALUES ('Micrófono', 300.00);
INSERT INTO producto (nombre, precio) VALUES ('Auriculares Bluetooth', 90.00);
INSERT INTO producto (nombre, precio) VALUES ('Cámara de Seguridad', 180.00);
INSERT INTO producto (nombre, precio) VALUES ('Luces LED', 40.00);
INSERT INTO producto (nombre, precio) VALUES ('Fuente de Poder', 120.00);
INSERT INTO producto (nombre, precio) VALUES ('Placa Base', 400.00);
INSERT INTO producto (nombre, precio) VALUES ('Memoria RAM 8GB', 75.00);
INSERT INTO producto (nombre, precio) VALUES ('Memoria RAM 16GB', 150.00);
INSERT INTO producto (nombre, precio) VALUES ('Tarjeta Gráfica', 500.00);
INSERT INTO producto (nombre, precio) VALUES ('CPU Intel i5', 250.00);
INSERT INTO producto (nombre, precio) VALUES ('CPU Intel i7', 350.00);
INSERT INTO producto (nombre, precio) VALUES ('SSD 256GB', 90.00);
INSERT INTO producto (nombre, precio) VALUES ('SSD 512GB', 150.00);
INSERT INTO producto (nombre, precio) VALUES ('SSD 1TB', 250.00);
INSERT INTO producto (nombre, precio) VALUES ('Disco Duro 2TB', 80.00);
INSERT INTO producto (nombre, precio) VALUES ('Gabinete para PC', 60.00);
INSERT INTO producto (nombre, precio) VALUES ('Ventilador para CPU', 40.00);
INSERT INTO producto (nombre, precio) VALUES ('Kit de Limpieza', 15.00);
INSERT INTO producto (nombre, precio) VALUES ('Software Antivirus', 50.00);
INSERT INTO producto (nombre, precio) VALUES ('Base Refrigerante', 25.00);
INSERT INTO producto (nombre, precio) VALUES ('Controlador de Juegos', 60.00);
INSERT INTO producto (nombre, precio) VALUES ('Auriculares para Juegos', 120.00);
INSERT INTO producto (nombre, precio) VALUES ('Consola de Juegos', 500.00);
INSERT INTO producto (nombre, precio) VALUES ('Joystick', 35.00);
INSERT INTO producto (nombre, precio) VALUES ('Tarjeta de Captura', 200.00);
INSERT INTO producto (nombre, precio) VALUES ('Monitor Ultrawide', 900.00);
INSERT INTO producto (nombre, precio) VALUES ('Impresora 3D', 1200.00);
INSERT INTO producto (nombre, precio) VALUES ('Escáner', 250.00);
INSERT INTO producto (nombre, precio) VALUES ('Módem', 100.00);
INSERT INTO producto (nombre, precio) VALUES ('Adaptador USB', 15.00);
INSERT INTO producto (nombre, precio) VALUES ('Altavoces', 80.00);
INSERT INTO producto (nombre, precio) VALUES ('Subwoofer', 150.00);
INSERT INTO producto (nombre, precio) VALUES ('Cámara Web', 70.00);
INSERT INTO producto (nombre, precio) VALUES ('Filtro de Privacidad', 40.00);
INSERT INTO producto (nombre, precio) VALUES ('Cables Organizadores', 10.00);
INSERT INTO producto (nombre, precio) VALUES ('Soporte para Monitor', 50.00);
INSERT INTO producto (nombre, precio) VALUES ('Lector de Tarjetas', 20.00);
INSERT INTO producto (nombre, precio) VALUES ('Disco Externo 4TB', 200.00);
INSERT INTO producto (nombre, precio) VALUES ('Switch HDMI', 30.00);
INSERT INTO producto (nombre, precio) VALUES ('Cable VGA', 15.00);
INSERT INTO producto (nombre, precio) VALUES ('Mochila para Laptop', 70.00);
INSERT INTO producto (nombre, precio) VALUES ('Brazo para Monitor', 90.00);
INSERT INTO producto (nombre, precio) VALUES ('Protector de Pantalla', 20.00);
INSERT INTO producto (nombre, precio) VALUES ('Cargador Inalámbrico', 40.00);
INSERT INTO producto (nombre, precio) VALUES ('Cable USB-C', 10.00);
INSERT INTO producto (nombre, precio) VALUES ('Docking Station', 150.00);
INSERT INTO producto (nombre, precio) VALUES ('Carcasa para Smartphone', 25.00);
INSERT INTO producto (nombre, precio) VALUES ('Estación de Carga', 50.00);
INSERT INTO producto (nombre, precio) VALUES ('Soporte para Laptop', 60.00);
INSERT INTO producto (nombre, precio) VALUES ('Microscopio Digital', 300.00);
INSERT INTO producto (nombre, precio) VALUES ('Cámara Deportiva', 250.00);
INSERT INTO producto (nombre, precio) VALUES ('Dron', 800.00);
INSERT INTO producto (nombre, precio) VALUES ('Cargador Solar', 70.00);
INSERT INTO producto (nombre, precio) VALUES ('Kit de Herramientas Electrónicas', 100.00);
INSERT INTO producto (nombre, precio) VALUES ('Lámpara LED Inteligente', 30.00);
INSERT INTO producto (nombre, precio) VALUES ('Smart Plug', 25.00);
INSERT INTO producto (nombre, precio) VALUES ('Termómetro Infrarrojo', 40.00);
INSERT INTO producto (nombre, precio) VALUES ('Báscula Digital', 50.00);
INSERT INTO producto (nombre, precio) VALUES ('Proyector Portátil', 400.00);
INSERT INTO producto (nombre, precio) VALUES ('Cámara Termográfica', 900.00);
INSERT INTO producto (nombre, precio) VALUES ('Sensor de Movimiento', 35.00);
INSERT INTO producto (nombre, precio) VALUES ('Estación Meteorológica', 120.00);
INSERT INTO producto (nombre, precio) VALUES ('Deshumidificador', 200.00);
INSERT INTO producto (nombre, precio) VALUES ('Purificador de Aire', 300.00);
INSERT INTO producto (nombre, precio) VALUES ('Lámpara UV', 50.00);
INSERT INTO producto (nombre, precio) VALUES ('Cortina Inteligente', 150.00);
INSERT INTO producto (nombre, precio) VALUES ('Aspiradora Inteligente', 400.00);
INSERT INTO producto (nombre, precio) VALUES ('Calentador Portátil', 100.00);
INSERT INTO producto (nombre, precio) VALUES ('Refrigerador Mini', 300.00);
INSERT INTO producto (nombre, precio) VALUES ('Hervidor Eléctrico', 70.00);
INSERT INTO producto (nombre, precio) VALUES ('Cafetera', 150.00);
INSERT INTO producto (nombre, precio) VALUES ('Placa de Inducción', 500.00);
INSERT INTO producto (nombre, precio) VALUES ('Robot de Cocina', 800.00);
INSERT INTO producto (nombre, precio) VALUES ('Freidora de Aire', 250.00);
INSERT INTO producto (nombre, precio) VALUES ('Parrilla Eléctrica', 300.00);
INSERT INTO producto (nombre, precio) VALUES ('Tostadora', 60.00);
INSERT INTO producto (nombre, precio) VALUES ('Horno Microondas', 400.00);
INSERT INTO producto (nombre, precio) VALUES ('Secador de Cabello', 100.00);
INSERT INTO producto (nombre, precio) VALUES ('Plancha de Vapor', 80.00);
INSERT INTO producto (nombre, precio) VALUES ('Licuadora', 120.00);
