INSERT INTO producto (id, nombre, precio) VALUES (1, 'Laptop', 1500.00);
INSERT INTO producto (id, nombre, precio) VALUES (2, 'Mouse', 50.00);
INSERT INTO producto (id, nombre, precio) VALUES (3, 'Teclado', 100.00);
INSERT INTO producto (id, nombre, precio) VALUES (4, 'Monitor', 200.00);
INSERT INTO producto (id, nombre, precio) VALUES (5, 'Impresora', 500.00);
INSERT INTO producto (id, nombre, precio) VALUES (6, 'Auriculares', 75.00);
INSERT INTO producto (id, nombre, precio) VALUES (7, 'Smartphone', 1200.00);
INSERT INTO producto (id, nombre, precio) VALUES (8, 'Tablet', 800.00);
INSERT INTO producto (id, nombre, precio) VALUES (9, 'Cámara', 900.00);
INSERT INTO producto (id, nombre, precio) VALUES (10, 'Disco Duro Externo', 150.00);
INSERT INTO producto (id, nombre, precio) VALUES (11, 'USB 32GB', 25.00);
INSERT INTO producto (id, nombre, precio) VALUES (12, 'Router', 120.00);
INSERT INTO producto (id, nombre, precio) VALUES (13, 'Switch Ethernet', 60.00);
INSERT INTO producto (id, nombre, precio) VALUES (14, 'Proyector', 1100.00);
INSERT INTO producto (id, nombre, precio) VALUES (15, 'Smartwatch', 250.00);
INSERT INTO producto (id, nombre, precio) VALUES (16, 'Cargador Rápido', 30.00);
INSERT INTO producto (id, nombre, precio) VALUES (17, 'Cable HDMI', 20.00);
INSERT INTO producto (id, nombre, precio) VALUES (18, 'Teclado Mecánico', 150.00);
INSERT INTO producto (id, nombre, precio) VALUES (19, 'Alfombrilla para Ratón', 10.00);
INSERT INTO producto (id, nombre, precio) VALUES (20, 'Caja de Herramientas', 80.00);
INSERT INTO producto (id, nombre, precio) VALUES (21, 'Micrófono', 300.00);
INSERT INTO producto (id, nombre, precio) VALUES (22, 'Auriculares Bluetooth', 90.00);
INSERT INTO producto (id, nombre, precio) VALUES (23, 'Cámara de Seguridad', 180.00);
INSERT INTO producto (id, nombre, precio) VALUES (24, 'Luces LED', 40.00);
INSERT INTO producto (id, nombre, precio) VALUES (25, 'Fuente de Poder', 120.00);
INSERT INTO producto (id, nombre, precio) VALUES (26, 'Placa Base', 400.00);
INSERT INTO producto (id, nombre, precio) VALUES (27, 'Memoria RAM 8GB', 75.00);
INSERT INTO producto (id, nombre, precio) VALUES (28, 'Memoria RAM 16GB', 150.00);
INSERT INTO producto (id, nombre, precio) VALUES (29, 'Tarjeta Gráfica', 500.00);
INSERT INTO producto (id, nombre, precio) VALUES (30, 'CPU Intel i5', 250.00);
INSERT INTO producto (id, nombre, precio) VALUES (31, 'CPU Intel i7', 350.00);
INSERT INTO producto (id, nombre, precio) VALUES (32, 'SSD 256GB', 90.00);
INSERT INTO producto (id, nombre, precio) VALUES (33, 'SSD 512GB', 150.00);
INSERT INTO producto (id, nombre, precio) VALUES (34, 'SSD 1TB', 250.00);
INSERT INTO producto (id, nombre, precio) VALUES (35, 'Disco Duro 2TB', 80.00);
INSERT INTO producto (id, nombre, precio) VALUES (36, 'Gabinete para PC', 60.00);
INSERT INTO producto (id, nombre, precio) VALUES (37, 'Ventilador para CPU', 40.00);
INSERT INTO producto (id, nombre, precio) VALUES (38, 'Kit de Limpieza', 15.00);
INSERT INTO producto (id, nombre, precio) VALUES (39, 'Software Antivirus', 50.00);
INSERT INTO producto (id, nombre, precio) VALUES (40, 'Base Refrigerante', 25.00);
INSERT INTO producto (id, nombre, precio) VALUES (41, 'Controlador de Juegos', 60.00);
INSERT INTO producto (id, nombre, precio) VALUES (42, 'Auriculares para Juegos', 120.00);
INSERT INTO producto (id, nombre, precio) VALUES (43, 'Consola de Juegos', 500.00);
INSERT INTO producto (id, nombre, precio) VALUES (44, 'Joystick', 35.00);
INSERT INTO producto (id, nombre, precio) VALUES (45, 'Tarjeta de Captura', 200.00);
INSERT INTO producto (id, nombre, precio) VALUES (46, 'Monitor Ultrawide', 900.00);
INSERT INTO producto (id, nombre, precio) VALUES (47, 'Impresora 3D', 1200.00);
INSERT INTO producto (id, nombre, precio) VALUES (48, 'Escáner', 250.00);
INSERT INTO producto (id, nombre, precio) VALUES (49, 'Módem', 100.00);
INSERT INTO producto (id, nombre, precio) VALUES (50, 'Adaptador USB', 15.00);
INSERT INTO producto (id, nombre, precio) VALUES (51, 'Altavoces', 80.00);
INSERT INTO producto (id, nombre, precio) VALUES (52, 'Subwoofer', 150.00);
INSERT INTO producto (id, nombre, precio) VALUES (53, 'Cámara Web', 70.00);
INSERT INTO producto (id, nombre, precio) VALUES (54, 'Filtro de Privacidad', 40.00);
INSERT INTO producto (id, nombre, precio) VALUES (55, 'Cables Organizadores', 10.00);
INSERT INTO producto (id, nombre, precio) VALUES (56, 'Soporte para Monitor', 50.00);
INSERT INTO producto (id, nombre, precio) VALUES (57, 'Lector de Tarjetas', 20.00);
INSERT INTO producto (id, nombre, precio) VALUES (58, 'Disco Externo 4TB', 200.00);
INSERT INTO producto (id, nombre, precio) VALUES (59, 'Switch HDMI', 30.00);
INSERT INTO producto (id, nombre, precio) VALUES (60, 'Cable VGA', 15.00);
INSERT INTO producto (id, nombre, precio) VALUES (61, 'Mochila para Laptop', 70.00);
INSERT INTO producto (id, nombre, precio) VALUES (62, 'Brazo para Monitor', 90.00);
INSERT INTO producto (id, nombre, precio) VALUES (63, 'Protector de Pantalla', 20.00);
INSERT INTO producto (id, nombre, precio) VALUES (64, 'Cargador Inalámbrico', 40.00);
INSERT INTO producto (id, nombre, precio) VALUES (65, 'Cable USB-C', 10.00);
INSERT INTO producto (id, nombre, precio) VALUES (66, 'Docking Station', 150.00);
INSERT INTO producto (id, nombre, precio) VALUES (67, 'Carcasa para Smartphone', 25.00);
INSERT INTO producto (id, nombre, precio) VALUES (68, 'Estación de Carga', 50.00);
INSERT INTO producto (id, nombre, precio) VALUES (69, 'Soporte para Laptop', 60.00);
INSERT INTO producto (id, nombre, precio) VALUES (70, 'Microscopio Digital', 300.00);
INSERT INTO producto (id, nombre, precio) VALUES (71, 'Cámara Deportiva', 250.00);
INSERT INTO producto (id, nombre, precio) VALUES (72, 'Dron', 800.00);
INSERT INTO producto (id, nombre, precio) VALUES (73, 'Cargador Solar', 70.00);
INSERT INTO producto (id, nombre, precio) VALUES (74, 'Kit de Herramientas Electrónicas', 100.00);
INSERT INTO producto (id, nombre, precio) VALUES (75, 'Lámpara LED Inteligente', 30.00);
INSERT INTO producto (id, nombre, precio) VALUES (76, 'Smart Plug', 25.00);
INSERT INTO producto (id, nombre, precio) VALUES (77, 'Termómetro Infrarrojo', 40.00);
INSERT INTO producto (id, nombre, precio) VALUES (78, 'Báscula Digital', 50.00);
INSERT INTO producto (id, nombre, precio) VALUES (79, 'Proyector Portátil', 400.00);
INSERT INTO producto (id, nombre, precio) VALUES (80, 'Cámara Termográfica', 900.00);
INSERT INTO producto (id, nombre, precio) VALUES (81, 'Sensor de Movimiento', 35.00);
INSERT INTO producto (id, nombre, precio) VALUES (82, 'Estación Meteorológica', 120.00);
INSERT INTO producto (id, nombre, precio) VALUES (83, 'Deshumidificador', 200.00);
INSERT INTO producto (id, nombre, precio) VALUES (84, 'Purificador de Aire', 300.00);
INSERT INTO producto (id, nombre, precio) VALUES (85, 'Lámpara UV', 50.00);
INSERT INTO producto (id, nombre, precio) VALUES (86, 'Cortina Inteligente', 150.00);
INSERT INTO producto (id, nombre, precio) VALUES (87, 'Aspiradora Inteligente', 400.00);
INSERT INTO producto (id, nombre, precio) VALUES (88, 'Calentador Portátil', 100.00);
INSERT INTO producto (id, nombre, precio) VALUES (89, 'Refrigerador Mini', 300.00);
INSERT INTO producto (id, nombre, precio) VALUES (90, 'Hervidor Eléctrico', 70.00);
INSERT INTO producto (id, nombre, precio) VALUES (91, 'Cafetera', 150.00);
INSERT INTO producto (id, nombre, precio) VALUES (92, 'Placa de Inducción', 500.00);
INSERT INTO producto (id, nombre, precio) VALUES (93, 'Robot de Cocina', 800.00);
INSERT INTO producto (id, nombre, precio) VALUES (94, 'Freidora de Aire', 250.00);
INSERT INTO producto (id, nombre, precio) VALUES (95, 'Parrilla Eléctrica', 300.00);
INSERT INTO producto (id, nombre, precio) VALUES (96, 'Tostadora', 60.00);
INSERT INTO producto (id, nombre, precio) VALUES (97, 'Horno Microondas', 400.00);
INSERT INTO producto (id, nombre, precio) VALUES (98, 'Secador de Cabello', 100.00);
INSERT INTO producto (id, nombre, precio) VALUES (99, 'Plancha de Vapor', 80.00);
INSERT INTO producto (id, nombre, precio) VALUES (100, 'Licuadora', 120.00);
